# Generated by Django 2.1.3 on 2018-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prenume',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='numar_telefon',
            field=models.IntegerField(default=0),
        ),
    ]
